### ISSUE TITLE
Issue on machine day: 30/01/24

### ISSUE THREAD

**Issue by rosesyrett** [bluesky/ophyd-async#109]
blueapi logs for i22

```
INFO:     127.0.0.1:34098 - "POST /tasks HTTP/1.1" 201 Created
INFO:blueapi.worker.reworker:Submitting: task_id='33018899-f7f9-420c-8f16-92db2e08d22e' task=RunPlan(name='linkam_plan', params={'heat_temp': 30, 'cool_temp': 0, 'start_temp': 30, 'cool_step': 5, 'heat_rate': 10, 'exposure': 0.1, 'heat_step': 5, 'num_frames': 10, 'cool_rate': 10}) is_complete=False is_pending=True errors=[]
INFO:blueapi.worker.reworker:Got new task: task_id='33018899-f7f9-420c-8f16-92db2e08d22e' task=RunPlan(name='linkam_plan', params={'heat_temp': 30, 'cool_temp': 0, 'start_temp': 30, 'cool_step': 5, 'heat_rate': 10, 'exposure': 0.1, 'heat_step': 5, 'num_frames': 10, 'cool_rate': 10}) is_complete=False is_pending=True errors=[]
INFO:blueapi.worker.task:Asked to run plan linkam_plan with {'heat_temp': 30, 'cool_temp': 0, 'start_temp': 30, 'cool_step': 5, 'heat_rate': 10, 'exposure': 0.1, 'heat_step': 5, 'num_frames': 10, 'cool_rate': 10}
INFO:bluesky:Executing plan <generator object BlueskyContext.wrap at 0x7fe17765f5b0>
INFO:bluesky.RE.state:Change state on <bluesky.run_engine.RunEngine object at 0x7fe1a1c99c10> from 'idle' -> 'running'
INFO:blueapi.messaging.stomptemplate:SENDING {"state": "RUNNING", "task_status": {"task_id": "33018899-f7f9-420c-8f16-92db2e08d22e", "task_complete": false, "task_failed": false}, "errors": [], "warnings": []} to /topic/public.worker.event
INFO:     127.0.0.1:34098 - "PUT /worker/task HTTP/1.1" 200 OK
ERROR:bluesky:Run aborted
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 500, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/p4p/client/asyncio.py", line 207, in put
    return (await self._put_one(name, values, request=request, get=get))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/p4p/client/asyncio.py", line 236, in _put_one
    value = await F
            ^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/dls_sw/i22/software/blueapi/scratch/ophyd-async/src/ophyd_async/epics/_backend/_p4p.py", line 260, in put
    await asyncio.wait_for(coro, timeout)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 502, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/dls_sw/i22/software/blueapi/scratch/bluesky/bluesky/run_engine.py", line 1508, in _run
    msg = self._plan_stack[-1].throw(stashed_exception or resp)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/blueapi/core/context.py", line 76, in wrap
    yield from wrapped_plan
  File "/venv/lib/python3.11/site-packages/blueapi/preprocessors/attach_metadata.py", line 36, in attach_metadata
    yield from bpp.inject_md_wrapper(
  File "/dls_sw/i22/software/blueapi/scratch/bluesky/bluesky/preprocessors.py", line 752, in inject_md_wrapper
    return (yield from msg_mutator(plan, _inject_md))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i22/software/blueapi/scratch/bluesky/bluesky/preprocessors.py", line 257, in msg_mutator
    msg = plan.throw(_e)
          ^^^^^^^^^^^^^^
  File "/dls_sw/i22/software/blueapi/scratch/i22-bluesky/src/i22_bluesky/plans/linkam.py", line 116, in linkam_plan
    yield from load_device(panda)
  File "/dls_sw/i22/software/blueapi/scratch/i22-bluesky/src/i22_bluesky/stubs/load.py", line 29, in load_device
    yield from set_signal_values(signals, phases)
  File "/dls_sw/i22/software/blueapi/scratch/ophyd-async/src/ophyd_async/core/device_save_loader.py", line 220, in set_signal_values
    yield from wait(f"load-phase{phase_number}")
  File "/dls_sw/i22/software/blueapi/scratch/bluesky/bluesky/plan_stubs.py", line 504, in wait
    return (yield Msg('wait', None, group=group, timeout=timeout))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i22/software/blueapi/scratch/bluesky/bluesky/preprocessors.py", line 251, in msg_mutator
    _s = yield msg
         ^^^^^^^^^
  File "/dls_sw/i22/software/blueapi/scratch/bluesky/bluesky/run_engine.py", line 2277, in _status_object_completed
    raise FailedStatus(ret) from exc
bluesky.utils.FailedStatus: <AsyncStatus, task: <coroutine object PvaSignalBackend.put at 0x7fe1764559c0>, errored: TimeoutError()>
INFO:bluesky.RE.state:Change state on <bluesky.run_engine.RunEngine object at 0x7fe1a1c99c10> from 'running' -> 'idle'
INFO:blueapi.messaging.stomptemplate:SENDING {"state": "IDLE", "task_status": {"task_id": "33018899-f7f9-420c-8f16-92db2e08d22e", "task_complete": false, "task_failed": false}, "errors": [], "warnings": []} to /topic/public.worker.event
ERROR:blueapi.worker.reworker:<AsyncStatus, task: <coroutine object PvaSignalBackend.put at 0x7fe1764559c0>, errored: TimeoutError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 500, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/p4p/client/asyncio.py", line 207, in put
    return (await self._put_one(name, values, request=request, get=get))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/p4p/client/asyncio.py", line 236, in _put_one
    value = await F
            ^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/dls_sw/i22/software/blueapi/scratch/ophyd-async/src/ophyd_async/epics/_backend/_p4p.py", line 260, in put
    await asyncio.wait_for(coro, timeout)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 502, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/blueapi/worker/reworker.py", line 235, in _cycle
    self._current.task.do_task(self._ctx)
  File "/venv/lib/python3.11/site-packages/blueapi/worker/task.py", line 33, in do_task
    ctx.run_engine(wrapped_plan_generator)
  File "/dls_sw/i22/software/blueapi/scratch/bluesky/bluesky/run_engine.py", line 904, in __call__
    plan_return = self._resume_task(init_func=_build_task)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i22/software/blueapi/scratch/bluesky/bluesky/run_engine.py", line 1043, in _resume_task
    raise exc
  File "/dls_sw/i22/software/blueapi/scratch/bluesky/bluesky/run_engine.py", line 1673, in _run
    raise err
  File "/dls_sw/i22/software/blueapi/scratch/bluesky/bluesky/run_engine.py", line 1508, in _run
    msg = self._plan_stack[-1].throw(stashed_exception or resp)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/blueapi/core/context.py", line 76, in wrap
    yield from wrapped_plan
  File "/venv/lib/python3.11/site-packages/blueapi/preprocessors/attach_metadata.py", line 36, in attach_metadata
    yield from bpp.inject_md_wrapper(
  File "/dls_sw/i22/software/blueapi/scratch/bluesky/bluesky/preprocessors.py", line 752, in inject_md_wrapper
    return (yield from msg_mutator(plan, _inject_md))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i22/software/blueapi/scratch/bluesky/bluesky/preprocessors.py", line 257, in msg_mutator
    msg = plan.throw(_e)
          ^^^^^^^^^^^^^^
  File "/dls_sw/i22/software/blueapi/scratch/i22-bluesky/src/i22_bluesky/plans/linkam.py", line 116, in linkam_plan
    yield from load_device(panda)
  File "/dls_sw/i22/software/blueapi/scratch/i22-bluesky/src/i22_bluesky/stubs/load.py", line 29, in load_device
    yield from set_signal_values(signals, phases)
  File "/dls_sw/i22/software/blueapi/scratch/ophyd-async/src/ophyd_async/core/device_save_loader.py", line 220, in set_signal_values
    yield from wait(f"load-phase{phase_number}")
  File "/dls_sw/i22/software/blueapi/scratch/bluesky/bluesky/plan_stubs.py", line 504, in wait
    return (yield Msg('wait', None, group=group, timeout=timeout))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i22/software/blueapi/scratch/bluesky/bluesky/preprocessors.py", line 251, in msg_mutator
    _s = yield msg
```

**Comment by rosesyrett** [comment]
This happened while trying to run the linkam plan. Seemed like there was some connection timeout for the panda, but the PV was not reported.
