### ISSUE TITLE
PVI connection handling unable to understand forward referencing in container

### ISSUE THREAD

**Issue by DiamondJoseph** [bluesky/ophyd-async#297]
NB. Posisbly related to blueapi's subprocess handling and pickling of objects/types.

Frustrating issue when trying to connect to a PandA that get_type_hints was unable to resolve the forward reference in Device.parent -> Optional[Device]

```shell
2024-05-10T11:16:18.157436353+01:00 ERROR:root:device `coros` raised unexpected exception NameError
2024-05-10T11:16:18.157457466+01:00 Traceback (most recent call last):
2024-05-10T11:16:18.157463660+01:00   File "/dls_sw/p45/software/blueapi/scratch/ophyd-async/src/ophyd_async/panda/_hdf_panda.py", line 47, in connect
2024-05-10T11:16:18.157469850+01:00     await fill_pvi_entries(self, self._prefix + "PVI", timeout=timeout, sim=sim)
2024-05-10T11:16:18.157475210+01:00   File "/dls_sw/p45/software/blueapi/scratch/ophyd-async/src/ophyd_async/epics/pvi/pvi.py", line 296, in fill_pvi_entries
2024-05-10T11:16:18.157480092+01:00     await _get_pvi_entries(root_entry, timeout=timeout)
2024-05-10T11:16:18.157484840+01:00   File "/dls_sw/p45/software/blueapi/scratch/ophyd-async/src/ophyd_async/epics/pvi/pvi.py", line 255, in _get_pvi_entries
2024-05-10T11:16:18.157489620+01:00     _verify_common_blocks(entry, entry.common_device_type)
2024-05-10T11:16:18.157494284+01:00   File "/dls_sw/p45/software/blueapi/scratch/ophyd-async/src/ophyd_async/epics/pvi/pvi.py", line 110, in _verify_common_blocks
2024-05-10T11:16:18.157498943+01:00     _verify_common_blocks(sub_sub_entry, sub_device)  # type: ignore
2024-05-10T11:16:18.157503558+01:00     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-10T11:16:18.157508238+01:00   File "/dls_sw/p45/software/blueapi/scratch/ophyd-async/src/ophyd_async/epics/pvi/pvi.py", line 98, in _verify_common_blocks
2024-05-10T11:16:18.157513275+01:00     common_sub_devices = get_type_hints(common_device)
2024-05-10T11:16:18.157518179+01:00                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-10T11:16:18.157523076+01:00   File "/usr/local/lib/python3.11/typing.py", line 2395, in get_type_hints
2024-05-10T11:16:18.157527806+01:00     hints[name] = _eval_type(value, globalns, localns)
2024-05-10T11:16:18.157532393+01:00                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-10T11:16:18.157537128+01:00   File "/usr/local/lib/python3.11/typing.py", line 381, in _eval_type
2024-05-10T11:16:18.157541739+01:00     return t._evaluate(globalns, localns, recursive_guard)
2024-05-10T11:16:18.157546316+01:00            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-10T11:16:18.157550985+01:00   File "/usr/local/lib/python3.11/typing.py", line 891, in _evaluate
2024-05-10T11:16:18.157568265+01:00     eval(self.__forward_code__, globalns, localns),
2024-05-10T11:16:18.157573000+01:00     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-10T11:16:18.157577485+01:00   File "<string>", line 1, in <module>
2024-05-10T11:16:18.157581927+01:00 NameError: name 'Optional' is not defined
2024-05-10T11:16:18.163794292+01:00 ERROR:    multiprocessing.pool.RemoteTraceback: 
2024-05-10T11:16:18.163812017+01:00 """
2024-05-10T11:16:18.163818069+01:00 Traceback (most recent call last):
2024-05-10T11:16:18.163822936+01:00   File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 125, in worker
2024-05-10T11:16:18.163827582+01:00     result = (True, func(*args, **kwds))
2024-05-10T11:16:18.163832271+01:00                     ^^^^^^^^^^^^^^^^^^^
2024-05-10T11:16:18.163836936+01:00   File "/venv/lib/python3.11/site-packages/blueapi/service/handler.py", line 185, in setup_handler
2024-05-10T11:16:18.163841625+01:00     handler = Handler(
2024-05-10T11:16:18.163846128+01:00               ^^^^^^^^
2024-05-10T11:16:18.163850847+01:00   File "/venv/lib/python3.11/site-packages/blueapi/service/handler.py", line 43, in __init__
2024-05-10T11:16:18.163855539+01:00     self._context.with_config(self._config.env)
2024-05-10T11:16:18.163868871+01:00   File "/venv/lib/python3.11/site-packages/blueapi/core/context.py", line 105, in with_config
2024-05-10T11:16:18.163876216+01:00     self.with_dodal_module(mod)
2024-05-10T11:16:18.163881147+01:00   File "/venv/lib/python3.11/site-packages/blueapi/core/context.py", line 144, in with_dodal_module
2024-05-10T11:16:18.163885904+01:00     for device in make_all_devices(module, **kwargs).values():
2024-05-10T11:16:18.163890405+01:00                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-10T11:16:18.163894861+01:00   File "/dls_sw/p45/software/blueapi/scratch/dodal/src/dodal/utils.py", line 128, in make_all_devices
2024-05-10T11:16:18.163899436+01:00     devices: dict[str, AnyDevice] = invoke_factories(factories, **kwargs)
2024-05-10T11:16:18.163904085+01:00                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-10T11:16:18.163908550+01:00   File "/dls_sw/p45/software/blueapi/scratch/dodal/src/dodal/utils.py", line 153, in invoke_factories
2024-05-10T11:16:18.163913143+01:00     devices[dependent_name] = factories[dependent_name](**params, **kwargs)
2024-05-10T11:16:18.163917660+01:00                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-10T11:16:18.163922246+01:00   File "/dls_sw/p45/software/blueapi/scratch/dodal/src/dodal/beamlines/p45.py", line 79, in panda2
2024-05-10T11:16:18.163926776+01:00     return device_instantiation(
2024-05-10T11:16:18.163931580+01:00            ^^^^^^^^^^^^^^^^^^^^^
2024-05-10T11:16:18.163936099+01:00   File "/dls_sw/p45/software/blueapi/scratch/dodal/src/dodal/utils.py", line 101, in wrapper
2024-05-10T11:16:18.163940635+01:00     return func(*args, **kwds)
2024-05-10T11:16:18.163945216+01:00            ^^^^^^^^^^^^^^^^^^^
2024-05-10T11:16:18.163949734+01:00   File "/dls_sw/p45/software/blueapi/scratch/dodal/src/dodal/beamlines/beamline_utils.py", line 113, in device_instantiation
2024-05-10T11:16:18.163954237+01:00     _wait_for_connection(device_instance, sim=fake)
2024-05-10T11:16:18.163958731+01:00   File "/dls_sw/p45/software/blueapi/scratch/dodal/src/dodal/beamlines/beamline_utils.py", line 53, in _wait_for_connection
2024-05-10T11:16:18.163963247+01:00     call_in_bluesky_event_loop(
2024-05-10T11:16:18.163967767+01:00   File "/dls_sw/p45/software/blueapi/scratch/bluesky/bluesky/run_engine.py", line 2782, in call_in_bluesky_event_loop
2024-05-10T11:16:18.163972302+01:00     return fut.result(timeout=timeout)
2024-05-10T11:16:18.163976788+01:00            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-10T11:16:18.163981344+01:00   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 456, in result
2024-05-10T11:16:18.163985766+01:00     return self.__get_result()
2024-05-10T11:16:18.163990350+01:00            ^^^^^^^^^^^^^^^^^^^
2024-05-10T11:16:18.163994847+01:00   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
2024-05-10T11:16:18.163999391+01:00     raise self._exception
2024-05-10T11:16:18.164003932+01:00   File "/dls_sw/p45/software/blueapi/scratch/ophyd-async/src/ophyd_async/core/utils.py", line 98, in wait_for_connection
2024-05-10T11:16:18.164008369+01:00     raise NotConnected(exceptions)
2024-05-10T11:16:18.164025666+01:00 ophyd_async.core.utils.NotConnected: 
2024-05-10T11:16:18.164030336+01:00 coros: NameError: name 'Optional' is not defined
2024-05-10T11:16:18.164034498+01:00 
2024-05-10T11:16:18.164038790+01:00 """
2024-05-10T11:16:18.164042721+01:00 
2024-05-10T11:16:18.164046982+01:00 The above exception was the direct cause of the following exception:
2024-05-10T11:16:18.164050965+01:00 
2024-05-10T11:16:18.164055307+01:00 Traceback (most recent call last):
2024-05-10T11:16:18.164063618+01:00   File "/venv/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
2024-05-10T11:16:18.164068621+01:00     async with self.lifespan_context(app) as maybe_state:
2024-05-10T11:16:18.164073272+01:00   File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__
2024-05-10T11:16:18.164077681+01:00     return await anext(self.gen)
2024-05-10T11:16:18.164082037+01:00            ^^^^^^^^^^^^^^^^^^^^^
2024-05-10T11:16:18.164086383+01:00   File "/venv/lib/python3.11/site-packages/blueapi/service/main.py", line 64, in lifespan
2024-05-10T11:16:18.164090696+01:00     setup_handler(config)
2024-05-10T11:16:18.164095013+01:00   File "/venv/lib/python3.11/site-packages/blueapi/service/main.py", line 48, in setup_handler
2024-05-10T11:16:18.164099621+01:00     handler.start()
2024-05-10T11:16:18.164104017+01:00   File "/venv/lib/python3.11/site-packages/blueapi/service/subprocess_handler.py", line 42, in start
2024-05-10T11:16:18.164108461+01:00     self._subprocess.apply(setup_handler, [self._config])
2024-05-10T11:16:18.164112747+01:00   File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 360, in apply
2024-05-10T11:16:18.164117235+01:00     return self.apply_async(func, args, kwds).get()
2024-05-10T11:16:18.164121626+01:00            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-10T11:16:18.164125932+01:00   File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 774, in get
2024-05-10T11:16:18.164130222+01:00     raise self._value
2024-05-10T11:16:18.164134756+01:00 ophyd_async.core.utils.NotConnected: 
2024-05-10T11:16:18.164139119+01:00 coros: NameError: name 'Optional' is not defined
2024-05-10T11:16:18.164143202+01:00 
2024-05-10T11:16:18.164147175+01:00 
2024-05-10T11:16:18.164163255+01:00 ERROR:    Application startup failed. Exiting.
```

**Comment by evalott100** [comment]
For posterity:

We found that this was a specific problem related to `future.__annotations__` alongside `get_type_annotations`. For whatever reason, in the blueapi build of ophyd-async, we would get an error where `Optional[Device]` (normally unpacked to `Union[None, Device] at runtime) was not defined, after taking out the optional we had the error that `Device` wasn't defined.

Since the behaviour of `future.__anotations__` is default in python > 3.10/3.11, we don't need this anyway.

**Comment by coretl** [comment]
Eventually this needs sorting, as annotations will all be like this in the end, but fortunately there is no set date for this [at the moment](https://docs.python.org/3/library/__future__.html#id2) so fine with this for now

**Comment by olliesilvester** [comment]
We use `from __future__ import annotations` lots in Hyperion, so we aren't able to use the Panda anymore until this is fixed
